name: Trigger Webhook After Docker Build

on:
  workflow_run:
    workflows: ["Build & Push to GHCR"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Send POST to Webhook
        run: |
          # curl -X POST ${{ secrets.WEBHOOK_URL }} \
          curl -X POST http://0.0.0.0:9000/webhook \
            -H "Content-Type: application/json" \
            -d '{
              "bot_name": "${{ github.repository }}"
            }'

